### ISSUE TITLE
Release Todos

### ISSUE THREAD

**Issue by ungoldman** [geobin-io/geobin.io#51]
- [ ] documentation
  - [x] API
    - [x] review & finalize
    - [x] publish to static pages for site
  - [x] readme
    - [x] consolidate/link server & client
  - [ ] style docs
  - [ ] provide navigation between docs
- [ ] client
  - [x] swap out angular-router for ui-router (#52)
  - [x] use `counts` route for # of requests on index (#53)
  - [x] implement separate list & detail views
  - [ ] finish user interface (#45)
- [x] server
  - [x] fix API GET requests -- `GET /api/1/create` not redirecting (it's creating!)
